version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /mnt/disk3/mongo_db_discord_bots:/data/db

  backend:
    build: ./backend
    environment:
      DISCORD_CLIENT_ID: your_discord_client_id
      DISCORD_CLIENT_SECRET: your_discord_client_secret
      SESSION_SECRET: your_session_secret
      MONGODB_URI: mongodb://mongo:27017/my-list-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
