version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb://mongo:27017/lists
      DISCORD_CLIENT_ID: DISCORD_CLIENT_ID
      DISCORD_CLIENT_SECRET: DISCORD_CLIENT_SECRET
      DISCORD_CALLBACK_URL: http://localhost:5000/auth/discord/callback

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /mnt/disk3/mongo_db_discord_bots:/data/db

volumes:
  - /mnt/disk3/mongo_db_discord_bots:
