version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    environment:
      DISCORD_CLIENT_ID: your_discord_client_id
      DISCORD_CLIENT_SECRET: your_discord_client_secret
      SESSION_SECRET: your_session_secret
      MONGODB_URI: mongodb+srv://<username>:<password>@cluster0.mongodb.net/<dbname>?retryWrites=true&w=majority
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo-data:
